// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package idempotencydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows
INSERT INTO platform.idempotency_keys (actor, method, path, key, request_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, now() + $6::interval)
ON CONFLICT DO NOTHING
`

type ClaimIdempotencyKeyParams struct {
	Actor       string
	Method      string
	Path        string
	Key         string
	RequestHash []byte
	Ttl         pgtype.Interval
}

// Claims the key for this request. A concurrent request with the same key blocks here on the unique
// index until the first transaction ends; 0 rows means the key was already completed.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey,
		arg.Actor,
		arg.Method,
		arg.Path,
		arg.Key,
		arg.RequestHash,
		arg.Ttl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE platform.idempotency_keys
SET response_status = $5, response_headers = $6, response_body = $7
WHERE actor = $1 AND method = $2 AND path = $3 AND key = $4
`

type CompleteIdempotencyKeyParams struct {
	Actor           string
	Method          string
	Path            string
	Key             string
	ResponseStatus  pgtype.Int2
	ResponseHeaders []byte
	ResponseBody    []byte
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.Actor,
		arg.Method,
		arg.Path,
		arg.Key,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
	)
	return err
}

const deleteExpiredIdempotencyKey = `-- name: DeleteExpiredIdempotencyKey :exec
DELETE FROM platform.idempotency_keys
WHERE actor = $1 AND method = $2 AND path = $3 AND key = $4 AND expires_at <= now()
`

type DeleteExpiredIdempotencyKeyParams struct {
	Actor  string
	Method string
	Path   string
	Key    string
}

// Lazy expiry for one key, so a key past its TTL starts fresh even before the cleanup job runs.
func (q *Queries) DeleteExpiredIdempotencyKey(ctx context.Context, arg DeleteExpiredIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKey,
		arg.Actor,
		arg.Method,
		arg.Path,
		arg.Key,
	)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM platform.idempotency_keys
WHERE ctid IN (
    SELECT ctid FROM platform.idempotency_keys
    WHERE expires_at <= now()
    LIMIT $1::int
)
`

// Periodic cleanup (relay-worker), in bounded batches so it never holds long locks.
func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_hash, response_status, response_headers, response_body
FROM platform.idempotency_keys
WHERE actor = $1 AND method = $2 AND path = $3 AND key = $4
FOR SHARE
`

type GetIdempotencyKeyParams struct {
	Actor  string
	Method string
	Path   string
	Key    string
}

type GetIdempotencyKeyRow struct {
	RequestHash     []byte
	ResponseStatus  pgtype.Int2
	ResponseHeaders []byte
	ResponseBody    []byte
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey,
		arg.Actor,
		arg.Method,
		arg.Path,
		arg.Key,
	)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
	)
	return i, err
}
