// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package idempotencydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformIdempotencyKey struct {
	Actor           string
	Method          string
	Path            string
	Key             string
	RequestHash     []byte
	ResponseStatus  pgtype.Int2
	ResponseHeaders []byte
	ResponseBody    []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}
