// Command genstubs writes api/unimplemented.gen.go: one method per operation of the pinned
// relay-contracts strict-server interface, each returning server.ErrNotImplemented (501). Modules
// replace stubs by implementing the operation on their own type and embedding api.Unimplemented.
// Run `make generate`; CI fails if the output drifts.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"reflect"

	relayapi "github.com/gracefulinfra/relay-contracts/gen/go/relayapi"
)

func main() {
	t := reflect.TypeFor[relayapi.StrictServerInterface]()
	var b bytes.Buffer
	b.WriteString("// Code generated by api/internal/genstubs. DO NOT EDIT.\n\n")
	b.WriteString("package api\n\n")
	b.WriteString("import (\n\t\"context\"\n\n\trelayapi \"github.com/gracefulinfra/relay-contracts/gen/go/relayapi\"\n\n")
	b.WriteString("\t\"github.com/gracefulinfra/relay-api/internal/platform/server\"\n)\n\n")
	fmt.Fprintf(&b, "// Operations is the number of operations in the pinned contract.\nconst Operations = %d\n\n", t.NumMethod())
	b.WriteString("// Unimplemented answers 501 for every operation in the contract.\ntype Unimplemented struct{}\n\n")
	b.WriteString("var _ relayapi.StrictServerInterface = Unimplemented{}\n")
	for i := range t.NumMethod() {
		m := t.Method(i)
		in, out := m.Type.In(1).Name(), m.Type.Out(0).Name()
		fmt.Fprintf(&b, "\n// %s answers 501.\nfunc (Unimplemented) %s(context.Context, relayapi.%s) (relayapi.%s, error) {\n\treturn nil, server.ErrNotImplemented\n}\n", m.Name, m.Name, in, out)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(os.Args[1], src, 0o600); err != nil { //nolint:gosec // developer tool; the path comes from go:generate
		log.Fatal(err)
	}
}
