// Code generated by api/internal/genstubs. DO NOT EDIT.

package api

import (
	"context"

	relayapi "github.com/gracefulinfra/relay-contracts/gen/go/relayapi"

	"github.com/gracefulinfra/relay-api/internal/platform/server"
)

// Operations is the number of operations in the pinned contract.
const Operations = 94

// Unimplemented answers 501 for every operation in the contract.
type Unimplemented struct{}

var _ relayapi.StrictServerInterface = Unimplemented{}

// AbandonFirstRelease answers 501.
func (Unimplemented) AbandonFirstRelease(context.Context, relayapi.AbandonFirstReleaseRequestObject) (relayapi.AbandonFirstReleaseResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ApproveChapterSet answers 501.
func (Unimplemented) ApproveChapterSet(context.Context, relayapi.ApproveChapterSetRequestObject) (relayapi.ApproveChapterSetResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ApproveRevision answers 501.
func (Unimplemented) ApproveRevision(context.Context, relayapi.ApproveRevisionRequestObject) (relayapi.ApproveRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ApproveTranscriptRevision answers 501.
func (Unimplemented) ApproveTranscriptRevision(context.Context, relayapi.ApproveTranscriptRevisionRequestObject) (relayapi.ApproveTranscriptRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CancelEpisodeSchedule answers 501.
func (Unimplemented) CancelEpisodeSchedule(context.Context, relayapi.CancelEpisodeScheduleRequestObject) (relayapi.CancelEpisodeScheduleResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ConfirmPublicationTarget answers 501.
func (Unimplemented) ConfirmPublicationTarget(context.Context, relayapi.ConfirmPublicationTargetRequestObject) (relayapi.ConfirmPublicationTargetResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateChapterSet answers 501.
func (Unimplemented) CreateChapterSet(context.Context, relayapi.CreateChapterSetRequestObject) (relayapi.CreateChapterSetResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateEpisode answers 501.
func (Unimplemented) CreateEpisode(context.Context, relayapi.CreateEpisodeRequestObject) (relayapi.CreateEpisodeResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateExport answers 501.
func (Unimplemented) CreateExport(context.Context, relayapi.CreateExportRequestObject) (relayapi.CreateExportResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreatePerson answers 501.
func (Unimplemented) CreatePerson(context.Context, relayapi.CreatePersonRequestObject) (relayapi.CreatePersonResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateRevision answers 501.
func (Unimplemented) CreateRevision(context.Context, relayapi.CreateRevisionRequestObject) (relayapi.CreateRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateRightsDocumentUpload answers 501.
func (Unimplemented) CreateRightsDocumentUpload(context.Context, relayapi.CreateRightsDocumentUploadRequestObject) (relayapi.CreateRightsDocumentUploadResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateRightsRecord answers 501.
func (Unimplemented) CreateRightsRecord(context.Context, relayapi.CreateRightsRecordRequestObject) (relayapi.CreateRightsRecordResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateSeason answers 501.
func (Unimplemented) CreateSeason(context.Context, relayapi.CreateSeasonRequestObject) (relayapi.CreateSeasonResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateShow answers 501.
func (Unimplemented) CreateShow(context.Context, relayapi.CreateShowRequestObject) (relayapi.CreateShowResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateTopic answers 501.
func (Unimplemented) CreateTopic(context.Context, relayapi.CreateTopicRequestObject) (relayapi.CreateTopicResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// CreateUpload answers 501.
func (Unimplemented) CreateUpload(context.Context, relayapi.CreateUploadRequestObject) (relayapi.CreateUploadResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// DecideRightsRecord answers 501.
func (Unimplemented) DecideRightsRecord(context.Context, relayapi.DecideRightsRecordRequestObject) (relayapi.DecideRightsRecordResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// DeleteEpisode answers 501.
func (Unimplemented) DeleteEpisode(context.Context, relayapi.DeleteEpisodeRequestObject) (relayapi.DeleteEpisodeResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// DeleteSeason answers 501.
func (Unimplemented) DeleteSeason(context.Context, relayapi.DeleteSeasonRequestObject) (relayapi.DeleteSeasonResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// DeleteShowGrant answers 501.
func (Unimplemented) DeleteShowGrant(context.Context, relayapi.DeleteShowGrantRequestObject) (relayapi.DeleteShowGrantResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// DiscardRevision answers 501.
func (Unimplemented) DiscardRevision(context.Context, relayapi.DiscardRevisionRequestObject) (relayapi.DiscardRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// DownloadExport answers 501.
func (Unimplemented) DownloadExport(context.Context, relayapi.DownloadExportRequestObject) (relayapi.DownloadExportResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetAsset answers 501.
func (Unimplemented) GetAsset(context.Context, relayapi.GetAssetRequestObject) (relayapi.GetAssetResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetChapterSet answers 501.
func (Unimplemented) GetChapterSet(context.Context, relayapi.GetChapterSetRequestObject) (relayapi.GetChapterSetResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetEpisode answers 501.
func (Unimplemented) GetEpisode(context.Context, relayapi.GetEpisodeRequestObject) (relayapi.GetEpisodeResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetEpisodeDelivery answers 501.
func (Unimplemented) GetEpisodeDelivery(context.Context, relayapi.GetEpisodeDeliveryRequestObject) (relayapi.GetEpisodeDeliveryResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetEpisodeReadiness answers 501.
func (Unimplemented) GetEpisodeReadiness(context.Context, relayapi.GetEpisodeReadinessRequestObject) (relayapi.GetEpisodeReadinessResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetExport answers 501.
func (Unimplemented) GetExport(context.Context, relayapi.GetExportRequestObject) (relayapi.GetExportResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetJob answers 501.
func (Unimplemented) GetJob(context.Context, relayapi.GetJobRequestObject) (relayapi.GetJobResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetMe answers 501.
func (Unimplemented) GetMe(context.Context, relayapi.GetMeRequestObject) (relayapi.GetMeResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetNetwork answers 501.
func (Unimplemented) GetNetwork(context.Context, relayapi.GetNetworkRequestObject) (relayapi.GetNetworkResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetPerson answers 501.
func (Unimplemented) GetPerson(context.Context, relayapi.GetPersonRequestObject) (relayapi.GetPersonResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetPublicEpisode answers 501.
func (Unimplemented) GetPublicEpisode(context.Context, relayapi.GetPublicEpisodeRequestObject) (relayapi.GetPublicEpisodeResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetPublicNetwork answers 501.
func (Unimplemented) GetPublicNetwork(context.Context, relayapi.GetPublicNetworkRequestObject) (relayapi.GetPublicNetworkResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetPublicShow answers 501.
func (Unimplemented) GetPublicShow(context.Context, relayapi.GetPublicShowRequestObject) (relayapi.GetPublicShowResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetPublicTranscript answers 501.
func (Unimplemented) GetPublicTranscript(context.Context, relayapi.GetPublicTranscriptRequestObject) (relayapi.GetPublicTranscriptResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetReleaseManifest answers 501.
func (Unimplemented) GetReleaseManifest(context.Context, relayapi.GetReleaseManifestRequestObject) (relayapi.GetReleaseManifestResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetRevision answers 501.
func (Unimplemented) GetRevision(context.Context, relayapi.GetRevisionRequestObject) (relayapi.GetRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetRightsRecord answers 501.
func (Unimplemented) GetRightsRecord(context.Context, relayapi.GetRightsRecordRequestObject) (relayapi.GetRightsRecordResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetSeason answers 501.
func (Unimplemented) GetSeason(context.Context, relayapi.GetSeasonRequestObject) (relayapi.GetSeasonResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetShow answers 501.
func (Unimplemented) GetShow(context.Context, relayapi.GetShowRequestObject) (relayapi.GetShowResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// GetTranscriptRevision answers 501.
func (Unimplemented) GetTranscriptRevision(context.Context, relayapi.GetTranscriptRevisionRequestObject) (relayapi.GetTranscriptRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListApprovals answers 501.
func (Unimplemented) ListApprovals(context.Context, relayapi.ListApprovalsRequestObject) (relayapi.ListApprovalsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListAuditEvents answers 501.
func (Unimplemented) ListAuditEvents(context.Context, relayapi.ListAuditEventsRequestObject) (relayapi.ListAuditEventsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListChapterSets answers 501.
func (Unimplemented) ListChapterSets(context.Context, relayapi.ListChapterSetsRequestObject) (relayapi.ListChapterSetsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListDeliveryReceipts answers 501.
func (Unimplemented) ListDeliveryReceipts(context.Context, relayapi.ListDeliveryReceiptsRequestObject) (relayapi.ListDeliveryReceiptsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListDestinations answers 501.
func (Unimplemented) ListDestinations(context.Context, relayapi.ListDestinationsRequestObject) (relayapi.ListDestinationsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListEpisodeAssets answers 501.
func (Unimplemented) ListEpisodeAssets(context.Context, relayapi.ListEpisodeAssetsRequestObject) (relayapi.ListEpisodeAssetsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListEpisodes answers 501.
func (Unimplemented) ListEpisodes(context.Context, relayapi.ListEpisodesRequestObject) (relayapi.ListEpisodesResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListExports answers 501.
func (Unimplemented) ListExports(context.Context, relayapi.ListExportsRequestObject) (relayapi.ListExportsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListFeedSnapshots answers 501.
func (Unimplemented) ListFeedSnapshots(context.Context, relayapi.ListFeedSnapshotsRequestObject) (relayapi.ListFeedSnapshotsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListJobs answers 501.
func (Unimplemented) ListJobs(context.Context, relayapi.ListJobsRequestObject) (relayapi.ListJobsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListPeople answers 501.
func (Unimplemented) ListPeople(context.Context, relayapi.ListPeopleRequestObject) (relayapi.ListPeopleResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListPublicEpisodes answers 501.
func (Unimplemented) ListPublicEpisodes(context.Context, relayapi.ListPublicEpisodesRequestObject) (relayapi.ListPublicEpisodesResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListPublicShows answers 501.
func (Unimplemented) ListPublicShows(context.Context, relayapi.ListPublicShowsRequestObject) (relayapi.ListPublicShowsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListPublicationTargets answers 501.
func (Unimplemented) ListPublicationTargets(context.Context, relayapi.ListPublicationTargetsRequestObject) (relayapi.ListPublicationTargetsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListReleaseManifests answers 501.
func (Unimplemented) ListReleaseManifests(context.Context, relayapi.ListReleaseManifestsRequestObject) (relayapi.ListReleaseManifestsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListRevisions answers 501.
func (Unimplemented) ListRevisions(context.Context, relayapi.ListRevisionsRequestObject) (relayapi.ListRevisionsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListRightsRecords answers 501.
func (Unimplemented) ListRightsRecords(context.Context, relayapi.ListRightsRecordsRequestObject) (relayapi.ListRightsRecordsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListSeasons answers 501.
func (Unimplemented) ListSeasons(context.Context, relayapi.ListSeasonsRequestObject) (relayapi.ListSeasonsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListShowGrants answers 501.
func (Unimplemented) ListShowGrants(context.Context, relayapi.ListShowGrantsRequestObject) (relayapi.ListShowGrantsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListShows answers 501.
func (Unimplemented) ListShows(context.Context, relayapi.ListShowsRequestObject) (relayapi.ListShowsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListStaffUsers answers 501.
func (Unimplemented) ListStaffUsers(context.Context, relayapi.ListStaffUsersRequestObject) (relayapi.ListStaffUsersResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListTopics answers 501.
func (Unimplemented) ListTopics(context.Context, relayapi.ListTopicsRequestObject) (relayapi.ListTopicsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ListTranscriptRevisions answers 501.
func (Unimplemented) ListTranscriptRevisions(context.Context, relayapi.ListTranscriptRevisionsRequestObject) (relayapi.ListTranscriptRevisionsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// PreviewFeed answers 501.
func (Unimplemented) PreviewFeed(context.Context, relayapi.PreviewFeedRequestObject) (relayapi.PreviewFeedResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// PublishEpisode answers 501.
func (Unimplemented) PublishEpisode(context.Context, relayapi.PublishEpisodeRequestObject) (relayapi.PublishEpisodeResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// PutEpisodeTopics answers 501.
func (Unimplemented) PutEpisodeTopics(context.Context, relayapi.PutEpisodeTopicsRequestObject) (relayapi.PutEpisodeTopicsResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// PutShowGrant answers 501.
func (Unimplemented) PutShowGrant(context.Context, relayapi.PutShowGrantRequestObject) (relayapi.PutShowGrantResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// RejectTranscriptRevision answers 501.
func (Unimplemented) RejectTranscriptRevision(context.Context, relayapi.RejectTranscriptRevisionRequestObject) (relayapi.RejectTranscriptRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// RenderNotes answers 501.
func (Unimplemented) RenderNotes(context.Context, relayapi.RenderNotesRequestObject) (relayapi.RenderNotesResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// RequestRevisionChanges answers 501.
func (Unimplemented) RequestRevisionChanges(context.Context, relayapi.RequestRevisionChangesRequestObject) (relayapi.RequestRevisionChangesResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// RequestTranscription answers 501.
func (Unimplemented) RequestTranscription(context.Context, relayapi.RequestTranscriptionRequestObject) (relayapi.RequestTranscriptionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// RetryAsset answers 501.
func (Unimplemented) RetryAsset(context.Context, relayapi.RetryAssetRequestObject) (relayapi.RetryAssetResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// RetryJob answers 501.
func (Unimplemented) RetryJob(context.Context, relayapi.RetryJobRequestObject) (relayapi.RetryJobResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// RetryPublicationTarget answers 501.
func (Unimplemented) RetryPublicationTarget(context.Context, relayapi.RetryPublicationTargetRequestObject) (relayapi.RetryPublicationTargetResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// RetryTranscription answers 501.
func (Unimplemented) RetryTranscription(context.Context, relayapi.RetryTranscriptionRequestObject) (relayapi.RetryTranscriptionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ReviseRevision answers 501.
func (Unimplemented) ReviseRevision(context.Context, relayapi.ReviseRevisionRequestObject) (relayapi.ReviseRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// ScheduleEpisode answers 501.
func (Unimplemented) ScheduleEpisode(context.Context, relayapi.ScheduleEpisodeRequestObject) (relayapi.ScheduleEpisodeResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// SubmitRevision answers 501.
func (Unimplemented) SubmitRevision(context.Context, relayapi.SubmitRevisionRequestObject) (relayapi.SubmitRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// TakedownAsset answers 501.
func (Unimplemented) TakedownAsset(context.Context, relayapi.TakedownAssetRequestObject) (relayapi.TakedownAssetResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UnpublishEpisode answers 501.
func (Unimplemented) UnpublishEpisode(context.Context, relayapi.UnpublishEpisodeRequestObject) (relayapi.UnpublishEpisodeResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UpdateChapterSet answers 501.
func (Unimplemented) UpdateChapterSet(context.Context, relayapi.UpdateChapterSetRequestObject) (relayapi.UpdateChapterSetResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UpdateNetwork answers 501.
func (Unimplemented) UpdateNetwork(context.Context, relayapi.UpdateNetworkRequestObject) (relayapi.UpdateNetworkResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UpdatePerson answers 501.
func (Unimplemented) UpdatePerson(context.Context, relayapi.UpdatePersonRequestObject) (relayapi.UpdatePersonResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UpdateRevision answers 501.
func (Unimplemented) UpdateRevision(context.Context, relayapi.UpdateRevisionRequestObject) (relayapi.UpdateRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UpdateRightsRecord answers 501.
func (Unimplemented) UpdateRightsRecord(context.Context, relayapi.UpdateRightsRecordRequestObject) (relayapi.UpdateRightsRecordResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UpdateSeason answers 501.
func (Unimplemented) UpdateSeason(context.Context, relayapi.UpdateSeasonRequestObject) (relayapi.UpdateSeasonResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UpdateShow answers 501.
func (Unimplemented) UpdateShow(context.Context, relayapi.UpdateShowRequestObject) (relayapi.UpdateShowResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UpdateTopic answers 501.
func (Unimplemented) UpdateTopic(context.Context, relayapi.UpdateTopicRequestObject) (relayapi.UpdateTopicResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UpdateTranscriptRevision answers 501.
func (Unimplemented) UpdateTranscriptRevision(context.Context, relayapi.UpdateTranscriptRevisionRequestObject) (relayapi.UpdateTranscriptRevisionResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// UploadManualTranscript answers 501.
func (Unimplemented) UploadManualTranscript(context.Context, relayapi.UploadManualTranscriptRequestObject) (relayapi.UploadManualTranscriptResponseObject, error) {
	return nil, server.ErrNotImplemented
}

// WithdrawRevisionApproval answers 501.
func (Unimplemented) WithdrawRevisionApproval(context.Context, relayapi.WithdrawRevisionApprovalRequestObject) (relayapi.WithdrawRevisionApprovalResponseObject, error) {
	return nil, server.ErrNotImplemented
}
